### ISSUE TITLE
how to load a capsule and run it locally..

### ISSUE THREAD

**Issue by UCNTFME** [opencv/open_vision_capsules#34]
Hi,
do you have any examples about load and run a capsule locally..

**Comment by apockill** [comment]
Hi! Thank you for the question. Here's some sample code, I hope this helps:

```python3
from pathlib import Path

import cv2

from vcap import BaseCapsule
from vcap.loading.capsule_loading import load_capsule
from vcap.loading.packaging import CAPSULE_EXTENSION, package_capsule

CAPSULE_DIRECTORY = "/home/alex/workspace/brainframe/capsules/detector_person_and_vehicle_fast"
IMAGE_PATH = "/home/alex/Downloads/d203acb013a62ec5b7892d95d6410928.jpg"


def package_and_load_capsule(capsule_directory) -> BaseCapsule:
    capsule_directory = Path(capsule_directory).absolute()
    capsule_name = capsule_directory.with_suffix(CAPSULE_EXTENSION).name
    packaged_capsule_path = capsule_directory.parent / capsule_name

    package_capsule(capsule_directory, packaged_capsule_path)

    return load_capsule(packaged_capsule_path)


def main():
    # Load the image for inference
    image = cv2.imread(IMAGE_PATH)

    # Load the capsule
    capsule = package_and_load_capsule(CAPSULE_DIRECTORY)

    # Run inference with the capsule
    results = capsule.process_frame(
        frame=image,
        detection_node=None,
        options=capsule.default_options,
        state=capsule.stream_state())

    # Print results
    print(results)


if __name__ == "__main__":
    main()

```

This script only supports loading and running a single capsule. In the future, I plan on adding some examples to the repository for how to run with multiple capsules in parallel (and have capsule scheduling involved).

With this script, you can now play with different things, such as making an inference loop (reading from a video file and feeding in frame-by-frame, you can also play with the `options` parameter (currently I have it using `capsule.default_options`, but different capsules have different configurable parameters.

**Comment by UCNTFME** [comment]
Hi！That's really a good example...

Thanks a lot for sharing the info. with me and looking forward to more examples ^^

**Comment by apockill** [comment]
I'm glad this helped. Feel free to ask any questions you might have- we're still working on making this library as easy to use as possible. :tada:
