### ISSUE TITLE
Brainframe client stream not working

### ISSUE THREAD

**Issue by gkomix88** [opencv/open_vision_capsules#37]
Hi,
Great work!
I try to install brainframe server with Ubuntu 20 in WSL2 on windows. I also use the brainframe client (windows version) connect using localhost. Connection success!

But when I try to connect to the webcam and load AVI file. It failed and does not shows any stream. I have registered in aotu.ai and obtained the community license (7 days).

Could anyone on the team assist? Thanks.

**Comment by apockill** [comment]
Hi gkomix, thank you for using BrainFrame and OpenVisionCapsules! This repository is specifically for the OpenVisionCapsules library, so I'll close this issue. 

I've seen and answered your post on the Aotu forum, however! [Link](https://forum.aotu.ai/t/video-file-wont-load-in-wsl/196).

**Comment by gkomix88** [comment]
Hi Alex,
The aotu.ai forum changed to read only mode, therefore I cannot reply to you in aotu.ai forum. 

I will reply to you here.
1. I will try using Virtual Box VM run Ubuntu OS on Windows. Just to confirm, the brainframe does not required GPU rite? Because VM the VirtualBox VM does not has access to GPU hardware.

2. The docker desktop on my PC stop running. Thus, I cannot retrieve the brainframe log file. Is there other way to retrieve the log file without running brainframe?

Thanks and hope to hear from you soon.

**Comment by apockill** [comment]
> 1. I will try using Virtual Box VM run Ubuntu OS on Windows. Just to confirm, the brainframe does not required GPU rite? Because VM the VirtualBox VM does not has access to GPU hardware.

BrainFrame does not require GPU. **However, if you load capsules that require GPU, they will run very slowly without GPU!**

Look at the **Hardware** section of the [Capsules Downloads Page](https://aotu.ai/docs/downloads/#capsules), and look for capsules that **don't** list GPU. Those will work fine in a CPU only enviornment 😊

![image](https://user-images.githubusercontent.com/1740412/125113347-6857bd80-e09d-11eb-8f48-dd55d02750a1.png)


> 2. The docker desktop on my PC stop running. Thus, I cannot retrieve the brainframe log file. Is there other way to retrieve the log file without running brainframe?

There's no need for BrainFrame to be runnning, the logs are handled by docker/docker-compose. Running `brainframe compose logs > logs.txt` will work as long as `docker` and `docker-compose` are installed.

---

I tested the forum, it appears it works fine? Let's continue the conversation there! 😊
