### ISSUE TITLE
Remove allow_growth=True so applications can configure this instead

### ISSUE THREAD

**Issue by velovix** [opencv/open_vision_capsules#8]
Right now we set GPU options for all GPUs to allow memory growth, and there isn't a way for applications to change this behavior. We should instead not touch the GPU options and let applications configure this value by setting the `TF_FORCE_GPU_ALLOW_GROWTH` environment variable.

**Comment by Nikhil1O1** [comment]
@velovix  can I work on this,I'm new but willing to contribute

**Comment by velovix** [comment]
@Nikhil1O1 That would be great! The change should be relatively simple. All you'd have to do is remove `allow_growth=True` from [here](https://github.com/opencv/open_vision_capsules/blob/43134e0aa78fb740798e67e6b8e686cd6cadaf9b/vcap/vcap/device_mapping.py#L32) and add some documentation mentioning the `TF_FORCE_GPU_ALLOW_GROWTH` environment variable and linking to the Tensorflow docs on the subject. Maybe that documentation should be on [this page](https://github.com/opencv/open_vision_capsules/blob/43134e0aa78fb740798e67e6b8e686cd6cadaf9b/docs/runtime_environment.rst). Let me know if you have any questions!

**Comment by Nikhil1O1** [comment]
Awesomene, I will see what i can do

**Comment by Nikhil1O1** [comment]
@velovix  If this one's solved in #24, please close this issue.
